# Generated by Django 3.0.5 on 2020-04-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arizona', '0002_auto_20200406_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post', to='Arizona.Tag'),
        ),
    ]
