# Generated by Django 3.0.5 on 2020-05-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arizona', '0005_auto_20200419_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_pub']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title']},
        ),
    ]
